# Introduction to NumPy

In [17]:
import numpy as np

In [18]:
np

<module 'numpy' from '/home/manu/miniconda3/envs/ml-zoomcamp/lib/python3.13/site-packages/numpy/__init__.py'>

In [19]:
np.zeros(5) # Creating an array of all the zeros of length 5

array([0., 0., 0., 0., 0.])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.full(10, 7.3) # Creates array of length 10 with element 7.3

array([7.3, 7.3, 7.3, 7.3, 7.3, 7.3, 7.3, 7.3, 7.3, 7.3])

In [22]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr

array([1, 2, 3, 4, 5, 6])

In [23]:
print(arr[4])
arr[-1] = 10
arr

5


array([ 1,  2,  3,  4,  5, 10])

In [24]:
np.arange(3, 10) # Creates sequence of number from (start, last) and exclusive of last 

array([3, 4, 5, 6, 7, 8, 9])

In [25]:
np.linspace(0, 1, 5)
# Creates an array of (start, last, parts) where parts is the pieces between the start and last  

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## Mutli-dementional arrays


In [26]:
np.zeros((5,2)) 
#Create an array with 5 rows and 2 columns 

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
n = np.array([
    [1, 2, 3],
    [3, 2, 1],
    [1, 2, 3],

])

n

array([[1, 2, 3],
       [3, 2, 1],
       [1, 2, 3]])

In [28]:
n[1]

array([3, 2, 1])

In [29]:
n[1][-1]

np.int64(1)

In [30]:
n[1, -1]

np.int64(1)

In [31]:
n[:,1] 
# this gives the whole column at position 1 (which in this case is the middle one )

array([2, 2, 2])

In [ ]:
n[0:1,1]
#This command selects the element in the first row and second column.


array([2])

## Randomly generated Array


In [41]:
np.random.rand(5,5)
# generating a random array of 5 rows and 5 columns 

array([[0.82336812, 0.40895015, 0.3530639 , 0.79683207, 0.91665191],
       [0.02992067, 0.54678426, 0.47546766, 0.51108681, 0.46302745],
       [0.31578978, 0.77000656, 0.30092313, 0.80024384, 0.21929343],
       [0.25382912, 0.57815555, 0.10137939, 0.82917278, 0.72846704],
       [0.1294495 , 0.56807595, 0.3121978 , 0.95433741, 0.92938692]])

In [44]:
# to get the fixed random numbers, we can fix the seed
np.random.seed(2)
np.random.rand(3,3)

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482],
       [0.20464863, 0.61927097, 0.29965467]])

In [ ]:
np.random.randn(3,3)
# this function gives an array of random numbers sampled from the standard normal (or Gaussian) distribution. This means the numbers will be centered around a mean of 0 with a standard deviation of 1. In simpler terms, you'll get a mix of positive and negative numbers, with most of them clustered close to zero.

array([[-0.45571477, -2.12452767,  0.54979824],
       [-1.16790025,  1.08006357, -3.4918143 ],
       [ 1.27004848, -0.48921489, -1.17598956]])

In [63]:
np.random.randint(2,10,(2,3))
# This will give array of 2 rows and 3 columns with a random integers from 2 and 10 but 10 is excluded 

array([[4, 9, 8],
       [5, 6, 7]])

## Element wise operation

In [84]:
a = np.arange(1, 4)
a 

array([1, 2, 3])

In [85]:
a + 1 # we can directly treat the array like a varible to do operation

array([2, 3, 4])

In [87]:
a *= 5
a

array([ 5, 10, 15])

In [89]:
# to check for each element 
a > 7

array([False,  True,  True])

In [92]:
# we can also do things like sum, min, max and even standard deviation with std
a.std()

np.float64(4.08248290463863)