## Basic LA

In [ ]:
# vector vector multiplication
import numpy as np


In [12]:
u = np.arange(1, 4)
v = np.arange(4, 7)
print(f"u: {u} \nv: {v}")

u: [1 2 3] 
v: [4 5 6]


In [16]:
u.shape[0] # give the lengh or the array

3

In [20]:
# dot product 
u.dot(v)


np.int64(32)

In [ ]:
# Matrix - vector multiplication
m = np.arange(1, 10).reshape((3,3)) 
# most common way to create a matrix is using np.array([],[],[]) but here what we do is 
# first we create an 1D array which is from 1 to 9 and then organise it into 3 by 3 (3 rows and 3 columns) 
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# for matric - vector multiplication the no. of coloumns in the matirx and the number of element in the vector should be same 
# to understand better how it works ->
def matrix_vector_multiplication(m, v):
    # Assert that the number of columns in the matrix (m) equals the number of elements in the vector (v)
    assert m.shape[1] == v.shape[0]

    # The number of rows in the matrix determines the size of our final result vector.
    n_rows = m.shape[0]

    # Create an empty result vector of the correct size, filled with zeros.
    result = np.zeros(n_rows)

    # Loop through each row of the matrix.
    for i in range(n_rows):
        # Calculate the dot product of the i-th row of the matrix (m[i]) and the vector (v).
        # Assign this value to the i-th element of our result vector.
        result[i] = m[i].dot(v)

    return result

In [34]:
matrix_vector_multiplication(m,v)

array([ 32.,  77., 122.])

In [ ]:
m.dot(v) # but this is the standard way, the above one was just for knowing behind the seen maths 
# same goes for matrix - matrix multiplication, using .dot()

array([ 32,  77, 122])

In [41]:
m2 = np.arange(9,18).reshape(3,3)
m.dot(m2)
# the important point here is that the number of columns in the first matrix must be same as the number of rows in the second matrix 

array([[ 78,  84,  90],
       [186, 201, 216],
       [294, 318, 342]])

In [43]:
# Identity martix
i = np.eye(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Inverse Matrix - only for square matrix
v = np.arange(1,5).reshape((2,2))
v_inv = np.linalg.inv(v)
v_inv

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [52]:
# product of matrix and it's inverse gives identity matrix
v_inv.dot(v)

# Note: Due to the nature of floating-point computer math, there might be sometimes very small numbers instead of a perfect zero, like 2.22e-16, which is effectively zero.

array([[1.00000000e+00, 0.00000000e+00],
       [2.22044605e-16, 1.00000000e+00]])